package org.nd4j.linalg.lossfunctions;

import org.junit.*;
import static org.junit.Assert.*;
import org.nd4j.linalg.api.ndarray.INDArray;

/**
 * The class <code>LossFunctionsTest</code> contains tests for the class <code>{@link LossFunctions}</code>.
 *
 * @generatedBy CodePro at 3/7/15 7:14 PM
 * @author saurabh
 * @version $Revision: 1.0 $
 */
public class LossFunctionsTest {
	/**
	 * Run the double score(INDArray,LossFunction,INDArray,double,boolean) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	@Test
	public void testScore_1()
		throws Exception {
		INDArray labels = null;
		LossFunctions.LossFunction lossFunction = LossFunctions.LossFunction.EXPLL;
		INDArray z = null;
		double l2 = 1.0;
		boolean useRegularization = true;

		double result = LossFunctions.score(labels, lossFunction, z, l2, useRegularization);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at org.nd4j.linalg.lossfunctions.LossFunctions.score(LossFunctions.java:48)
		assertEquals(0.0, result, 0.1);
	}

	/**
	 * Run the double score(INDArray,LossFunction,INDArray,double,boolean) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	@Test
	public void testScore_2()
		throws Exception {
		INDArray labels = null;
		LossFunctions.LossFunction lossFunction = LossFunctions.LossFunction.EXPLL;
		INDArray z = null;
		double l2 = 1.0;
		boolean useRegularization = true;

		double result = LossFunctions.score(labels, lossFunction, z, l2, useRegularization);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at org.nd4j.linalg.lossfunctions.LossFunctions.score(LossFunctions.java:48)
		assertEquals(0.0, result, 0.1);
	}

	/**
	 * Run the double score(INDArray,LossFunction,INDArray,double,boolean) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	@Test
	public void testScore_3()
		throws Exception {
		INDArray labels = null;
		LossFunctions.LossFunction lossFunction = LossFunctions.LossFunction.EXPLL;
		INDArray z = null;
		double l2 = 1.0;
		boolean useRegularization = true;

		double result = LossFunctions.score(labels, lossFunction, z, l2, useRegularization);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at org.nd4j.linalg.lossfunctions.LossFunctions.score(LossFunctions.java:48)
		assertEquals(0.0, result, 0.1);
	}

	/**
	 * Run the double score(INDArray,LossFunction,INDArray,double,boolean) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	@Test
	public void testScore_4()
		throws Exception {
		INDArray labels = null;
		LossFunctions.LossFunction lossFunction = LossFunctions.LossFunction.EXPLL;
		INDArray z = null;
		double l2 = 1.0;
		boolean useRegularization = true;

		double result = LossFunctions.score(labels, lossFunction, z, l2, useRegularization);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at org.nd4j.linalg.lossfunctions.LossFunctions.score(LossFunctions.java:48)
		assertEquals(0.0, result, 0.1);
	}

	/**
	 * Run the double score(INDArray,LossFunction,INDArray,double,boolean) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	@Test
	public void testScore_5()
		throws Exception {
		INDArray labels = null;
		LossFunctions.LossFunction lossFunction = LossFunctions.LossFunction.EXPLL;
		INDArray z = null;
		double l2 = 1.0;
		boolean useRegularization = true;

		double result = LossFunctions.score(labels, lossFunction, z, l2, useRegularization);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at org.nd4j.linalg.lossfunctions.LossFunctions.score(LossFunctions.java:48)
		assertEquals(0.0, result, 0.1);
	}

	/**
	 * Run the double score(INDArray,LossFunction,INDArray,double,boolean) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	@Test
	public void testScore_6()
		throws Exception {
		INDArray labels = null;
		LossFunctions.LossFunction lossFunction = LossFunctions.LossFunction.EXPLL;
		INDArray z = null;
		double l2 = 1.0;
		boolean useRegularization = true;

		double result = LossFunctions.score(labels, lossFunction, z, l2, useRegularization);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at org.nd4j.linalg.lossfunctions.LossFunctions.score(LossFunctions.java:48)
		assertEquals(0.0, result, 0.1);
	}

	/**
	 * Run the double score(INDArray,LossFunction,INDArray,double,boolean) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	@Test
	public void testScore_7()
		throws Exception {
		INDArray labels = null;
		LossFunctions.LossFunction lossFunction = LossFunctions.LossFunction.EXPLL;
		INDArray z = null;
		double l2 = 1.0;
		boolean useRegularization = true;

		double result = LossFunctions.score(labels, lossFunction, z, l2, useRegularization);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at org.nd4j.linalg.lossfunctions.LossFunctions.score(LossFunctions.java:48)
		assertEquals(0.0, result, 0.1);
	}

	/**
	 * Run the double score(INDArray,LossFunction,INDArray,double,boolean) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	@Test
	public void testScore_8()
		throws Exception {
		INDArray labels = null;
		LossFunctions.LossFunction lossFunction = LossFunctions.LossFunction.EXPLL;
		INDArray z = null;
		double l2 = 1.0;
		boolean useRegularization = true;

		double result = LossFunctions.score(labels, lossFunction, z, l2, useRegularization);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at org.nd4j.linalg.lossfunctions.LossFunctions.score(LossFunctions.java:48)
		assertEquals(0.0, result, 0.1);
	}

	/**
	 * Run the double score(INDArray,LossFunction,INDArray,double,boolean) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	@Test
	public void testScore_9()
		throws Exception {
		INDArray labels = null;
		LossFunctions.LossFunction lossFunction = LossFunctions.LossFunction.EXPLL;
		INDArray z = null;
		double l2 = 1.0;
		boolean useRegularization = true;

		double result = LossFunctions.score(labels, lossFunction, z, l2, useRegularization);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at org.nd4j.linalg.lossfunctions.LossFunctions.score(LossFunctions.java:48)
		assertEquals(0.0, result, 0.1);
	}

	/**
	 * Run the double score(INDArray,LossFunction,INDArray,double,boolean) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	@Test
	public void testScore_10()
		throws Exception {
		INDArray labels = null;
		LossFunctions.LossFunction lossFunction = LossFunctions.LossFunction.EXPLL;
		INDArray z = null;
		double l2 = 1.0;
		boolean useRegularization = false;

		double result = LossFunctions.score(labels, lossFunction, z, l2, useRegularization);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at org.nd4j.linalg.lossfunctions.LossFunctions.score(LossFunctions.java:48)
		assertEquals(0.0, result, 0.1);
	}

	/**
	 * Perform pre-test initialization.
	 *
	 * @throws Exception
	 *         if the initialization fails for some reason
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	@Before
	public void setUp()
		throws Exception {
		// add additional set up code here
	}

	/**
	 * Perform post-test clean-up.
	 *
	 * @throws Exception
	 *         if the clean-up fails for some reason
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	@After
	public void tearDown()
		throws Exception {
		// Add additional tear down code here
	}

	/**
	 * Launch the test.
	 *
	 * @param args the command line arguments
	 *
	 * @generatedBy CodePro at 3/7/15 7:14 PM
	 */
	public static void main(String[] args) {
		new org.junit.runner.JUnitCore().run(LossFunctionsTest.class);
	}
}